name: ilac_takip
description: "Aile İlaç Takip Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

  # Bildirimler
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  android_alarm_manager_plus: ^4.0.0

  # Veri Saklama
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  # assets:
  #   - assets/icon.png